import json
import logging
from typing import Dict, Any, Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)

def generate_business_report(
    metrics: Dict[str, Any],
    dataset_name: str = "Hotel Management System",
    output_file: str = "business_summary.md"
) -> str:
    """
    Generate a professional business report for the Hotel Management data.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = [
        f"# 🏨 รายงานสรุปการบริหารจัดการ: {dataset_name}",
        f"**วันที่สร้างรายงาน:** {timestamp}",
        "",
        "## 📊 สรุปภาพรวม (Summary)",
        f"- **จำนวนลูกค้าทั้งหมด:** {metrics.get('total_customers', 0)} ราย",
        f"- **ยอดการจองรวม:** {metrics.get('total_bookings', 0)} ครั้ง",
        f"- **อัตราการเข้าพัก:** {metrics.get('occupancy_rate', 0):.2f}%",
        "",
        "## 💰 สถานะทางการเงิน (Financials)",
        f"- **รายได้รวม:** {metrics.get('total_revenue', 0):,.2f} บาท",
        f"- **รายจ่ายรวม:** {metrics.get('total_expenses', 0):,.2f} บาท",
        f"- **กำไรสุทธิ:** {metrics.get('net_profit', 0):,.2f} บาท",
        "",
        "## 🔍 การวิเคราะห์ข้อมูล (AI Insights)",
        metrics.get('ai_analysis', 'ไม่มีข้อมูลการวิเคราะห์ในขณะนี้'),
        "",
        "## 💡 ข้อเสนอแนะเชิงกลยุทธ์",
        "- [ ] เพิ่มการตลาดผ่านช่องทางออนไลน์ในช่วง Low Season",
        "- [ ] ปรับปรุงระบบการจองให้เป็นอัตโนมัติมากขึ้น",
        "",
        "---",
        "**Generated by OpenClaw: Perfect Edition (Data Analyst Module)**"
    ]

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("
".join(report))
    
    return output_file
